# Generated by Django 5.2.1 on 2025-05-20 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0002_careercategory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CareerCategory',
        ),
    ]
